# Generated by Django 4.2.2 on 2023-06-26 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anketa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('b_date', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('old_work', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('additions', models.CharField(max_length=255, null=True)),
                ('create_at', models.DateTimeField(blank=True)),
                ('select', models.BooleanField(default=False, null=True)),
                ('rezerv', models.BooleanField(default=False, null=True)),
            ],
            options={
                'verbose_name_plural': "Anketa ma'lumotlari",
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=255, verbose_name='Bolim nomi')),
            ],
            options={
                'verbose_name_plural': "Bo'lim",
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=255, verbose_name='Ish positsiyasi')),
            ],
            options={
                'verbose_name_plural': 'Positsiya',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(default=1, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Telegram user',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_title', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=500)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': "Bosh ish o'rinlari ruyxati",
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('b_date', models.DateField()),
                ('phone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=1000)),
                ('date_join', models.DateField(verbose_name='Ishga qabul qilingan sanasi')),
                ('status', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.department')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.position')),
            ],
            options={
                'verbose_name_plural': 'Ishchilar',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.position'),
        ),
    ]
