# Generated by Django 4.2.2 on 2023-07-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_department_position_staff_department_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='comment',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
