# Generated by Django 4.2.2 on 2023-07-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_execution', models.DateTimeField()),
            ],
        ),
    ]
