# Generated by Django 4.2.2 on 2023-07-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_gender_alter_staff_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='contract_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
