# Generated by Django 4.2.2 on 2023-07-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_staff_contract_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
