# Generated by Django 4.2.2 on 2023-07-22 09:26

import birthday.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_staff_gender_delete_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday_dayofyear_internal', models.PositiveSmallIntegerField(default=None, editable=False, null=True)),
                ('birthday', birthday.fields.BirthdayField()),
            ],
        ),
    ]
