# Generated by Django 4.2.2 on 2023-07-22 09:31

import birthday.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_testss'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='b_date_dayofyear_internal',
            field=models.PositiveSmallIntegerField(default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='b_date',
            field=birthday.fields.BirthdayField(),
        ),
    ]
