# Generated by Django 4.2.2 on 2023-07-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_staff_b_date_dayofyear_internal_alter_staff_b_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='b_date_dayofyear_internal',
        ),
        migrations.AlterField(
            model_name='staff',
            name='b_date',
            field=models.DateField(),
        ),
    ]
