# Generated by Django 4.2.2 on 2023-07-22 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_staff_b_date_dayofyear_internal_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testss',
        ),
    ]
