from django.urls import path
from django.contrib.auth import views as auth_views
from .views import (
    index,
    anketa,
    work,
    user,
    select_anketa,
    rezerv,
    staff,
    delete_staff,
    edit_staff,
    add_staff,
    active_staff,
    false_staff,
    send_sms,
    send_message,
    today_birthday,
    data,
    activ_data,
    false_data,
    anketa_data,
    rezerv_data,
    weekly_birthday,
    edit_todo,
    add_todo,
    delete_todo,
    delete_work,
    detail_staff,
    StaffDetailView,
    delete_user

)

urlpatterns = [

    path('', index, name='index'),
    path('anketa/', anketa, name='anketa'),
    path('work/', work, name='work'),
    path('user/', user, name='user'),
    path('sendsms/<int:staff_id>/', send_sms, name='send_sms'),
    path('sendmessage/', send_message, name='send_message'),
    path('select/', select_anketa, name='select'),
    path('rezervs/', rezerv, name='rezervs'),
    path('staffs/', staff, name='staffs'),
    path('today/bithday', today_birthday, name='today_bithday'),
    path('weekly/bithday', weekly_birthday, name='weekly_birthday'),
    path('edit/staff', edit_staff, name='edit_staff'),
    path('staff/edit/<int:staff_id>/', edit_staff, name='edit_staff'),
    path('delete_staff/<int:staff_id>/', delete_staff, name='delete_staff'),
    path('add/staff/', add_staff, name='add_staff'),
    path('active/staff/', active_staff, name='active_staff'),
    path('false/staff/', false_staff, name='false_staff'),
    path('data/', data, name='staff_data'),
    path('active/data/', activ_data, name='active_data'),
    path('false/data/', false_data, name='false_data'),
    path('anketa/data/', anketa_data, name='anketa_data'),
    path('rezerv/data/', rezerv_data, name='rezerv_data'),
    path('edit/todo/<int:todo_id>/', edit_todo, name='edit_todo'),
    path('todo/add/', add_todo, name='add_todo'),
    path('todo/delete/<int:item_id>/', delete_todo, name='delete_todo'),
    path('work/delete/<int:item_id>/', delete_work, name='delete_work'),
    path('detail/staff/<int:pk>/', StaffDetailView.as_view(), name='detail_staff'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('user/delete/<int:item_id>/', delete_user, name='delete_user'),

]